spring:
  datasource:
    url: jdbc:sqlserver://ravindra123.database.windows.net:1433;database=databaseabc;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adminroot
    password: Ravindra@12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8086


